# Numpy
- Numpy is a core python package which stands for numerical python.
- It is a fundamental package for numerical computations in python.
- It supports high-performance N-dimensional array objects that can be used for processing multidimensional data.

## Numpy Array
- A numpy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers.
- The number of dimensions is the rank of the array.
- The shape of an array is a tuple of integers giving size of the array along each dimension.

### Creation of array

In [2]:
import numpy as np

In [13]:
# creating array using nested python list
arr = np.array([1,2,3,4,5,6],dtype=int);
print(arr)

[1 2 3 4 5 6]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
print(len(arr))

6


In [6]:
print(arr.ndim)

1


In [7]:
print(arr.shape)

(6,)


In [8]:
arr2 = arr.reshape(3,2) # it won't affect the original array
print(arr2)
arr2.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [9]:
print(arr)

[1 2 3 4 5 6]


In [11]:
arr3 = arr.reshape(2,-1)
print(arr3)

[[1 2 3]
 [4 5 6]]


In [12]:
arr3.ndim

2

In [14]:
# initialising numpy array using nested python lists
my_list1 = [1,2,3]
my_list2 = [4,5,6]
my_list3 = [7,8,9]

arr4 = np.array([my_list1,my_list2,my_list3])
print(arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
arr4.shape

(3, 3)

In [17]:
arr4.ndim

2

In [18]:
arr4.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

## Numpy-Attributes

In [20]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [21]:
# reshaping an ndarray
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [22]:
r=range(24)
print(r)

range(0, 24)


In [23]:
# an array of evenly spaced numbers
a = np.arange(24)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [24]:
# reshaping the array 'a'
b = a.reshape(6,4,1);
print(b)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


## Arithmetic Operations 

In [25]:
x = np.array([[1,2,3],[4,5,6]],dtype=float);
y = np.array([[7,8,9],[1,2,3]],dtype=float);
print(x)
print(y)

[[1. 2. 3.]
 [4. 5. 6.]]
[[7. 8. 9.]
 [1. 2. 3.]]


### numpy.add() : elementwise addition b/w two arrays
syntax : numpy.add(arr1,arr2)

In [26]:
np.add(x,y)

array([[ 8., 10., 12.],
       [ 5.,  7.,  9.]])

In [27]:
x+y

array([[ 8., 10., 12.],
       [ 5.,  7.,  9.]])

### numpy.subtract() : elementwise subtraction b/w two arrays
syntax : numpy.subtract(arr1,arr2)

In [28]:
np.subtract(x,y)

array([[-6., -6., -6.],
       [ 3.,  3.,  3.]])

In [29]:
x-y

array([[-6., -6., -6.],
       [ 3.,  3.,  3.]])

### numpy.multiply() : elementwise multiplication b/w two arrays
syntax : numpy.multiply(arr1,arr2)

In [30]:
np.multiply(x,y)

array([[ 7., 16., 27.],
       [ 4., 10., 18.]])

In [31]:
x*y

array([[ 7., 16., 27.],
       [ 4., 10., 18.]])

In [33]:
# dot product
a = np.array([[1,2],[3,4]]);
b = np.array([[5,6],[7,8]]);
a.dot(b)

array([[19, 22],
       [43, 50]])

In [34]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [35]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [36]:
np.divide(a,b)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

### numpy.sum() : returns the sum of all array elements over a given axis
syntax : numpy.sum(array,axis)

In [39]:
print(np.sum(x))
print(x)

21.0
[[1. 2. 3.]
 [4. 5. 6.]]


In [41]:
np.sum(x,axis=0) # compute sum of each column

array([5., 7., 9.])

In [43]:
np.sum(x,axis=1) # compute sum of each row

array([ 6., 15.])